//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libras.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap a_big {
            get {
                object obj = ResourceManager.GetObject("a_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a_br {
            get {
                object obj = ResourceManager.GetObject("a_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a_img {
            get {
                object obj = ResourceManager.GetObject("a_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a_lib {
            get {
                object obj = ResourceManager.GetObject("a_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_big {
            get {
                object obj = ResourceManager.GetObject("b_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_br {
            get {
                object obj = ResourceManager.GetObject("b_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_img {
            get {
                object obj = ResourceManager.GetObject("b_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_lib {
            get {
                object obj = ResourceManager.GetObject("b_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c_big {
            get {
                object obj = ResourceManager.GetObject("c_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c_br {
            get {
                object obj = ResourceManager.GetObject("c_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c_img {
            get {
                object obj = ResourceManager.GetObject("c_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c_lib {
            get {
                object obj = ResourceManager.GetObject("c_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d_big {
            get {
                object obj = ResourceManager.GetObject("d_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d_br {
            get {
                object obj = ResourceManager.GetObject("d_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d_img {
            get {
                object obj = ResourceManager.GetObject("d_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d_lib {
            get {
                object obj = ResourceManager.GetObject("d_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_big {
            get {
                object obj = ResourceManager.GetObject("e_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_br {
            get {
                object obj = ResourceManager.GetObject("e_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_img {
            get {
                object obj = ResourceManager.GetObject("e_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e_lib {
            get {
                object obj = ResourceManager.GetObject("e_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap f_big {
            get {
                object obj = ResourceManager.GetObject("f_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap f_br {
            get {
                object obj = ResourceManager.GetObject("f_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap f_img {
            get {
                object obj = ResourceManager.GetObject("f_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap f_lib {
            get {
                object obj = ResourceManager.GetObject("f_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g_big {
            get {
                object obj = ResourceManager.GetObject("g_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g_br {
            get {
                object obj = ResourceManager.GetObject("g_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g_img {
            get {
                object obj = ResourceManager.GetObject("g_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g_lib {
            get {
                object obj = ResourceManager.GetObject("g_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_big {
            get {
                object obj = ResourceManager.GetObject("h_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_br {
            get {
                object obj = ResourceManager.GetObject("h_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_img {
            get {
                object obj = ResourceManager.GetObject("h_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_lib {
            get {
                object obj = ResourceManager.GetObject("h_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap i_big {
            get {
                object obj = ResourceManager.GetObject("i_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap i_br {
            get {
                object obj = ResourceManager.GetObject("i_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap i_img {
            get {
                object obj = ResourceManager.GetObject("i_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap i_lib {
            get {
                object obj = ResourceManager.GetObject("i_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap j_big {
            get {
                object obj = ResourceManager.GetObject("j_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap j_br {
            get {
                object obj = ResourceManager.GetObject("j_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap j_img {
            get {
                object obj = ResourceManager.GetObject("j_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap j_lib {
            get {
                object obj = ResourceManager.GetObject("j_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k_big {
            get {
                object obj = ResourceManager.GetObject("k_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k_br {
            get {
                object obj = ResourceManager.GetObject("k_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k_img {
            get {
                object obj = ResourceManager.GetObject("k_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k_lib {
            get {
                object obj = ResourceManager.GetObject("k_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap l_big {
            get {
                object obj = ResourceManager.GetObject("l_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap l_br {
            get {
                object obj = ResourceManager.GetObject("l_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap l_img {
            get {
                object obj = ResourceManager.GetObject("l_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap l_lib {
            get {
                object obj = ResourceManager.GetObject("l_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_big {
            get {
                object obj = ResourceManager.GetObject("m_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_br {
            get {
                object obj = ResourceManager.GetObject("m_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_img {
            get {
                object obj = ResourceManager.GetObject("m_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_lib {
            get {
                object obj = ResourceManager.GetObject("m_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_big {
            get {
                object obj = ResourceManager.GetObject("n_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_br {
            get {
                object obj = ResourceManager.GetObject("n_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_img {
            get {
                object obj = ResourceManager.GetObject("n_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_lib {
            get {
                object obj = ResourceManager.GetObject("n_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap o_big {
            get {
                object obj = ResourceManager.GetObject("o_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap o_br {
            get {
                object obj = ResourceManager.GetObject("o_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap o_img {
            get {
                object obj = ResourceManager.GetObject("o_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap o_lib {
            get {
                object obj = ResourceManager.GetObject("o_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_big {
            get {
                object obj = ResourceManager.GetObject("p_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_br {
            get {
                object obj = ResourceManager.GetObject("p_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_img {
            get {
                object obj = ResourceManager.GetObject("p_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p_lib {
            get {
                object obj = ResourceManager.GetObject("p_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap q_big {
            get {
                object obj = ResourceManager.GetObject("q_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap q_br {
            get {
                object obj = ResourceManager.GetObject("q_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap q_img {
            get {
                object obj = ResourceManager.GetObject("q_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap q_lib {
            get {
                object obj = ResourceManager.GetObject("q_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap r_big {
            get {
                object obj = ResourceManager.GetObject("r_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap r_br {
            get {
                object obj = ResourceManager.GetObject("r_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap r_img {
            get {
                object obj = ResourceManager.GetObject("r_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap r_lib {
            get {
                object obj = ResourceManager.GetObject("r_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_big {
            get {
                object obj = ResourceManager.GetObject("s_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_br {
            get {
                object obj = ResourceManager.GetObject("s_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_img {
            get {
                object obj = ResourceManager.GetObject("s_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_lib {
            get {
                object obj = ResourceManager.GetObject("s_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t_big {
            get {
                object obj = ResourceManager.GetObject("t_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t_br {
            get {
                object obj = ResourceManager.GetObject("t_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t_img {
            get {
                object obj = ResourceManager.GetObject("t_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t_lib {
            get {
                object obj = ResourceManager.GetObject("t_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap u_big {
            get {
                object obj = ResourceManager.GetObject("u_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap u_br {
            get {
                object obj = ResourceManager.GetObject("u_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap u_img {
            get {
                object obj = ResourceManager.GetObject("u_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap u_lib {
            get {
                object obj = ResourceManager.GetObject("u_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v_big {
            get {
                object obj = ResourceManager.GetObject("v_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v_br {
            get {
                object obj = ResourceManager.GetObject("v_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v_img {
            get {
                object obj = ResourceManager.GetObject("v_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v_lib {
            get {
                object obj = ResourceManager.GetObject("v_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w_big {
            get {
                object obj = ResourceManager.GetObject("w_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w_br {
            get {
                object obj = ResourceManager.GetObject("w_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w_img {
            get {
                object obj = ResourceManager.GetObject("w_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w_lib {
            get {
                object obj = ResourceManager.GetObject("w_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_big {
            get {
                object obj = ResourceManager.GetObject("x_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_br {
            get {
                object obj = ResourceManager.GetObject("x_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_img {
            get {
                object obj = ResourceManager.GetObject("x_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_lib {
            get {
                object obj = ResourceManager.GetObject("x_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap y_big {
            get {
                object obj = ResourceManager.GetObject("y_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap y_br {
            get {
                object obj = ResourceManager.GetObject("y_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap y_img {
            get {
                object obj = ResourceManager.GetObject("y_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap y_lib {
            get {
                object obj = ResourceManager.GetObject("y_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap z_big {
            get {
                object obj = ResourceManager.GetObject("z_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap z_br {
            get {
                object obj = ResourceManager.GetObject("z_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap z_img {
            get {
                object obj = ResourceManager.GetObject("z_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap z_lib {
            get {
                object obj = ResourceManager.GetObject("z_lib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
